export const actionTypes = {
  REGISTRATION_REQUEST: 'REGISTRATION_REQUEST',
  REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',
  REGISTRATION_FAIL: 'REGISTRATION_FAIL',

  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',

  REDIRECT_TO_LOGIN_PAGE: 'REDIRECT_TO_LOGIN_PAGE'
};